# Generated by Django 3.0.5 on 2020-06-04 23:22

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Category = apps.get_model("petitions", "Category")
    category = Category(title="Незаконна забудова")
    category.save()
    category = Category(title="Гіпермаркет")
    category.save()
    category = Category(title="Треба категорія")
    category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='answer',
            field=models.TextField(default='', max_length=2000),
        ),

        migrations.RunPython(forwards_func),
    ]
