# Generated by Django 3.0.5 on 2020-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='answer',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
