# Generated by Django 3.0.5 on 2020-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_petition_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='answer',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
