# Generated by Django 3.0.5 on 2020-05-11 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0003_auto_20200510_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
