# Generated by Django 3.0.5 on 2020-05-11 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0004_auto_20200511_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='voters',
            field=models.ManyToManyField(related_name='voted_petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
