import Petition from '../models/petition';

const descriptions = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed tincidunt diam. Maecenas sit amet risus eu libero viverra accumsan at nec lacus. Nulla facilisi. Maecenas auctor risus sed leo tristique fermentum. Phasellus cursus, ligula ut tempor accumsan, eros eros tristique orci, eu porta justo felis quis nisi. Aliquam pharetra porta leo a suscipit. Maecenas maximus gravida enim, ac fermentum libero eleifend eu. Fusce sed aliquam dui. Proin nec eleifend magna.\n' +
  '\n' +
  'Phasellus sed pretium velit. Suspendisse imperdiet tincidunt maximus. Aenean condimentum, metus in tristique vestibulum, elit nunc sagittis tellus, sodales imperdiet elit felis eget mi. Praesent nec maximus urna. Nullam malesuada dignissim sapien sed rutrum. Fusce porta, massa eget facilisis consequat, justo ligula viverra arcu, sed finibus erat ante id dui. Proin sed justo enim. Nullam volutpat placerat tortor, sed feugiat libero condimentum vel. In suscipit viverra leo a malesuada. Nullam convallis, sapien eu accumsan finibus, nisl neque vulputate mauris, vel iaculis diam lacus ut ex. Donec at dignissim purus, eu blandit nibh. Phasellus viverra luctus tortor, non laoreet leo scelerisque faucibus. Pellentesque nec turpis neque. Morbi malesuada nulla at est ultricies sagittis. Nulla sit amet enim venenatis, efficitur metus vitae, posuere odio. Phasellus vulputate dictum urna eget interdum.\n' +
  '\n' +
  'Nullam lobortis dui ut purus pellentesque sagittis. Etiam mattis, arcu et luctus tincidunt, sem lorem vestibulum magna, a porttitor enim orci ac sapien. Fusce non leo ac urna aliquam mattis quis sagittis ex. Vestibulum vel lacus mauris. Vivamus fringilla elit lorem, id pretium metus tempor ut. Duis tincidunt eros eu tortor tincidunt ornare. Suspendisse nisi metus, finibus eu iaculis id, bibendum nec massa. Aliquam dolor libero, aliquam sed justo ac, egestas blandit mi. Aenean eu urna bibendum, ornare ligula ut, varius tellus. Curabitur condimentum suscipit tortor, aliquet malesuada magna euismod sit amet. Nam vestibulum nulla convallis, eleifend dui ac, elementum nisi. In eget arcu enim. Praesent ac nunc molestie, vulputate ante ac, efficitur diam. Praesent vel mollis libero. Mauris convallis ipsum varius eleifend pulvinar.\n' +
  '\n' +
  'Curabitur sed sem tortor. Nullam condimentum commodo erat, id tempus turpis euismod quis. Proin leo urna, aliquam vitae eros quis, laoreet fringilla lorem. Etiam tempor turpis ac metus pulvinar gravida. Aenean porttitor imperdiet ipsum, sit amet commodo mi aliquet et. Suspendisse convallis erat eu turpis pretium, ac laoreet nunc hendrerit. Proin ornare nisi quis ultrices viverra. Fusce ut volutpat eros. Praesent ut odio mauris. Donec vel libero finibus, placerat dolor facilisis, auctor massa. Nam mi lorem, tristique id vulputate dignissim, luctus vel urna. Vivamus tempus lacus feugiat, sodales turpis et, rutrum metus. Ut molestie eu libero sed dignissim. Morbi posuere congue malesuada.',
  'Duis maximus, orci ut dapibus vehicula, metus eros pellentesque lorem, eu tristique justo leo a elit. Sed dui mauris, dictum id est sed, sollicitudin congue massa. Etiam mattis nunc quis libero condimentum, quis convallis lectus rutrum. Phasellus at nibh odio. Ut et fermentum neque. Quisque commodo maximus massa, eget dapibus metus. Integer viverra venenatis nunc, at placerat arcu dapibus eget. Suspendisse in arcu odio. Nam tempus nunc ut mauris vulputate pretium. Aliquam erat volutpat. Sed viverra accumsan dui. Vivamus eleifend purus nisi, eu suscipit tellus ultrices dictum.\n' +
  '\n' +
  'Proin felis felis, pulvinar vitae eros at, pellentesque posuere erat. Morbi ut erat a magna cursus mollis. Ut sit amet leo ut massa mattis interdum. Mauris porta, felis sed accumsan maximus, lorem dolor rutrum nunc, sit amet pharetra elit neque sed odio. Duis non libero nec est lobortis sollicitudin ac non mauris. Integer auctor, nunc at malesuada dignissim, quam ex porta nibh, non suscipit erat ante ut dolor. Etiam scelerisque finibus orci, ac sodales arcu lacinia at. Maecenas vehicula et urna vel gravida. In id erat bibendum, sodales diam varius, pharetra nibh. Duis venenatis suscipit facilisis. Nunc et ipsum augue.\n' +
  '\n' +
  'Vestibulum at mauris leo. Donec ante metus, ullamcorper ac tempus at, congue eu sapien. Nulla varius neque nibh, a imperdiet odio volutpat sollicitudin. Suspendisse et ipsum libero. Vivamus maximus dolor vitae facilisis semper. Curabitur sodales dapibus convallis. Pellentesque tempor dapibus augue, vel tincidunt dolor sagittis non. Sed posuere, urna ut placerat fermentum, nibh nibh ultricies sem, at feugiat enim quam ut ipsum. Mauris sit amet mattis magna. Duis malesuada, dolor ac pretium lobortis, tortor arcu hendrerit eros, in vulputate odio risus a mi. Pellentesque nibh ante, elementum in ultricies a, tristique eu neque.',
  'Pellentesque nisl diam, dictum sollicitudin nulla sed, scelerisque faucibus ligula. Maecenas in orci a lectus pulvinar pulvinar. Integer pharetra molestie turpis, in dictum mi molestie eget. Aliquam tempus pretium dolor eget tempus. Mauris dolor orci, fermentum ac pretium vitae, posuere vel elit. Quisque vestibulum nulla eget est dignissim porttitor. Aenean at lectus mauris. Etiam dolor lorem, varius sit amet ex vitae, interdum ullamcorper est. Sed lacinia eros nibh, non eleifend purus vehicula eu. Donec et nibh dapibus, tincidunt massa quis, lacinia risus. Pellentesque ipsum nunc, venenatis facilisis massa a, dapibus viverra arcu. Proin consequat sem velit, sed tincidunt metus bibendum a. Aenean turpis metus, sollicitudin vel sem ac, dignissim ultrices quam. Fusce ultricies nibh libero, eget rutrum libero porttitor ut.\n' +
  '\n' +
  'Cras magna nisl, suscipit at metus in, fermentum luctus risus. Fusce convallis neque et sapien convallis porttitor a sed ante. Praesent eget pretium velit. Aenean mauris tellus, convallis nec suscipit a, lacinia vitae libero. Integer vulputate aliquam mollis. Donec ac maximus sem. Morbi id massa imperdiet, viverra ligula non, bibendum lectus.',
  'Pellentesque nisl diam, dictum sollicitudin nulla sed, scelerisque faucibus ligula. Maecenas in orci a lectus pulvinar pulvinar. Integer pharetra molestie turpis, in dictum mi molestie eget. Aliquam tempus pretium dolor eget tempus. Mauris dolor orci, fermentum ac pretium vitae, posuere vel elit. Quisque vestibulum nulla eget est dignissim porttitor. Aenean at lectus mauris. Etiam dolor lorem, varius sit amet ex vitae, interdum ullamcorper est. Sed lacinia eros nibh, non eleifend purus vehicula eu. Donec et nibh dapibus, tincidunt massa quis, lacinia risus. Pellentesque ipsum nunc, venenatis facilisis massa a, dapibus viverra arcu. Proin consequat sem velit, sed tincidunt metus bibendum a. Aenean turpis metus, sollicitudin vel sem ac, dignissim ultrices quam. Fusce ultricies nibh libero, eget rutrum libero porttitor ut.\n' +
  '\n' +
  'Cras magna nisl, suscipit at metus in, fermentum luctus risus. Fusce convallis neque et sapien convallis porttitor a sed ante. Praesent eget pretium velit. Aenean mauris tellus, convallis nec suscipit a, lacinia vitae libero. Integer vulputate aliquam mollis. Donec ac maximus sem. Morbi id massa imperdiet, viverra ligula non, bibendum lectus.\n' +
  '\n' +
  'Donec at dapibus leo. Proin sed eros non mi porttitor ultrices. Ut nec sem egestas ex sollicitudin posuere. Nulla aliquet libero nec risus posuere, sed convallis justo rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In imperdiet purus vel nibh aliquam imperdiet. Cras mi dui, interdum ac commodo et, vehicula non mi. Ut erat ante, pretium eget vulputate id, efficitur a tortor. Quisque id massa et augue efficitur condimentum. Nullam a gravida sem, a eleifend tortor. Aenean ut elit magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu metus facilisis, tincidunt felis nec, tincidunt massa. Sed ac orci urna. Pellentesque non eleifend ante. Donec elementum enim at ornare mollis.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed tincidunt diam. Maecenas sit amet risus eu libero viverra accumsan at nec lacus. Nulla facilisi. Maecenas auctor risus sed leo tristique fermentum. Phasellus cursus, ligula ut tempor accumsan, eros eros tristique orci, eu porta justo felis quis nisi. Aliquam pharetra porta leo a suscipit. Maecenas maximus gravida enim, ac fermentum libero eleifend eu. Fusce sed aliquam dui. Proin nec eleifend magna.\n' +
  '\n' +
  'Phasellus sed pretium velit. Suspendisse imperdiet tincidunt maximus. Aenean condimentum, metus in tristique vestibulum, elit nunc sagittis tellus, sodales imperdiet elit felis eget mi. Praesent nec maximus urna. Nullam malesuada dignissim sapien sed rutrum. Fusce porta, massa eget facilisis consequat, justo ligula viverra arcu, sed finibus erat ante id dui. Proin sed justo enim. Nullam volutpat placerat tortor, sed feugiat libero condimentum vel. In suscipit viverra leo a malesuada. Nullam convallis, sapien eu accumsan finibus, nisl neque vulputate mauris, vel iaculis diam lacus ut ex. Donec at dignissim purus, eu blandit nibh. Phasellus viverra luctus tortor, non laoreet leo scelerisque faucibus. Pellentesque nec turpis neque. Morbi malesuada nulla at est ultricies sagittis. Nulla sit amet enim venenatis, efficitur metus vitae, posuere odio. Phasellus vulputate dictum urna eget interdum.\n' +
  '\n' +
  'Nullam lobortis dui ut purus pellentesque sagittis. Etiam mattis, arcu et luctus tincidunt, sem lorem vestibulum magna, a porttitor enim orci ac sapien. Fusce non leo ac urna aliquam mattis quis sagittis ex. Vestibulum vel lacus mauris. Vivamus fringilla elit lorem, id pretium metus tempor ut. Duis tincidunt eros eu tortor tincidunt ornare. Suspendisse nisi metus, finibus eu iaculis id, bibendum nec massa. Aliquam dolor libero, aliquam sed justo ac, egestas blandit mi. Aenean eu urna bibendum, ornare ligula ut, varius tellus. Curabitur condimentum suscipit tortor, aliquet malesuada magna euismod sit amet. Nam vestibulum nulla convallis, eleifend dui ac, elementum nisi. In eget arcu enim. Praesent ac nunc molestie, vulputate ante ac, efficitur diam. Praesent vel mollis libero. Mauris convallis ipsum varius eleifend pulvinar.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed tincidunt diam. Maecenas sit amet risus eu libero viverra accumsan at nec lacus. Nulla facilisi. Maecenas auctor risus sed leo tristique fermentum. Phasellus cursus, ligula ut tempor accumsan, eros eros tristique orci, eu porta justo felis quis nisi. Aliquam pharetra porta leo a suscipit. Maecenas maximus gravida enim, ac fermentum libero eleifend eu. Fusce sed aliquam dui. Proin nec eleifend magna.\n' +
  '\n' +
  'Phasellus sed pretium velit. Suspendisse imperdiet tincidunt maximus. Aenean condimentum, metus in tristique vestibulum, elit nunc sagittis tellus, sodales imperdiet elit felis eget mi. Praesent nec maximus urna. Nullam malesuada dignissim sapien sed rutrum. Fusce porta, massa eget facilisis consequat, justo ligula viverra arcu, sed finibus erat ante id dui. Proin sed justo enim. Nullam volutpat placerat tortor, sed feugiat libero condimentum vel. In suscipit viverra leo a malesuada. Nullam convallis, sapien eu accumsan finibus, nisl neque vulputate mauris, vel iaculis diam lacus ut ex. Donec at dignissim purus, eu blandit nibh. Phasellus viverra luctus tortor, non laoreet leo scelerisque faucibus. Pellentesque nec turpis neque. Morbi malesuada nulla at est ultricies sagittis. Nulla sit amet enim venenatis, efficitur metus vitae, posuere odio. Phasellus vulputate dictum urna eget interdum.\n' +
  '\n' +
  'Nullam lobortis dui ut purus pellentesque sagittis. Etiam mattis, arcu et luctus tincidunt, sem lorem vestibulum magna, a porttitor enim orci ac sapien. Fusce non leo ac urna aliquam mattis quis sagittis ex. Vestibulum vel lacus mauris. Vivamus fringilla elit lorem, id pretium metus tempor ut. Duis tincidunt eros eu tortor tincidunt ornare. Suspendisse nisi metus, finibus eu iaculis id, bibendum nec massa. Aliquam dolor libero, aliquam sed justo ac, egestas blandit mi. Aenean eu urna bibendum, ornare ligula ut, varius tellus. Curabitur condimentum suscipit tortor, aliquet malesuada magna euismod sit amet. Nam vestibulum nulla convallis, eleifend dui ac, elementum nisi. In eget arcu enim. Praesent ac nunc molestie, vulputate ante ac, efficitur diam. Praesent vel mollis libero. Mauris convallis ipsum varius eleifend pulvinar.',
  'Curabitur sed sem tortor. Nullam condimentum commodo erat, id tempus turpis euismod quis. Proin leo urna, aliquam vitae eros quis, laoreet fringilla lorem. Etiam tempor turpis ac metus pulvinar gravida. Aenean porttitor imperdiet ipsum, sit amet commodo mi aliquet et. Suspendisse convallis erat eu turpis pretium, ac laoreet nunc hendrerit. Proin ornare nisi quis ultrices viverra. Fusce ut volutpat eros. Praesent ut odio mauris. Donec vel libero finibus, placerat dolor facilisis, auctor massa. Nam mi lorem, tristique id vulputate dignissim, luctus vel urna. Vivamus tempus lacus feugiat, sodales turpis et, rutrum metus. Ut molestie eu libero sed dignissim. Morbi posuere congue malesuada.\n' +
  '\n' +
  'Duis maximus, orci ut dapibus vehicula, metus eros pellentesque lorem, eu tristique justo leo a elit. Sed dui mauris, dictum id est sed, sollicitudin congue massa. Etiam mattis nunc quis libero condimentum, quis convallis lectus rutrum. Phasellus at nibh odio. Ut et fermentum neque. Quisque commodo maximus massa, eget dapibus metus. Integer viverra venenatis nunc, at placerat arcu dapibus eget. Suspendisse in arcu odio. Nam tempus nunc ut mauris vulputate pretium. Aliquam erat volutpat. Sed viverra accumsan dui. Vivamus eleifend purus nisi, eu suscipit tellus ultrices dictum.\n' +
  '\n' +
  'Proin felis felis, pulvinar vitae eros at, pellentesque posuere erat. Morbi ut erat a magna cursus mollis. Ut sit amet leo ut massa mattis interdum. Mauris porta, felis sed accumsan maximus, lorem dolor rutrum nunc, sit amet pharetra elit neque sed odio. Duis non libero nec est lobortis sollicitudin ac non mauris. Integer auctor, nunc at malesuada dignissim, quam ex porta nibh, non suscipit erat ante ut dolor. Etiam scelerisque finibus orci, ac sodales arcu lacinia at. Maecenas vehicula et urna vel gravida. In id erat bibendum, sodales diam varius, pharetra nibh. Duis venenatis suscipit facilisis. Nunc et ipsum augue.',
  'Curabitur sed sem tortor. Nullam condimentum commodo erat, id tempus turpis euismod quis. Proin leo urna, aliquam vitae eros quis, laoreet fringilla lorem. Etiam tempor turpis ac metus pulvinar gravida. Aenean porttitor imperdiet ipsum, sit amet commodo mi aliquet et. Suspendisse convallis erat eu turpis pretium, ac laoreet nunc hendrerit. Proin ornare nisi quis ultrices viverra. Fusce ut volutpat eros. Praesent ut odio mauris. Donec vel libero finibus, placerat dolor facilisis, auctor massa. Nam mi lorem, tristique id vulputate dignissim, luctus vel urna. Vivamus tempus lacus feugiat, sodales turpis et, rutrum metus. Ut molestie eu libero sed dignissim. Morbi posuere congue malesuada.\n' +
  '\n' +
  'Duis maximus, orci ut dapibus vehicula, metus eros pellentesque lorem, eu tristique justo leo a elit. Sed dui mauris, dictum id est sed, sollicitudin congue massa. Etiam mattis nunc quis libero condimentum, quis convallis lectus rutrum. Phasellus at nibh odio. Ut et fermentum neque. Quisque commodo maximus massa, eget dapibus metus. Integer viverra venenatis nunc, at placerat arcu dapibus eget. Suspendisse in arcu odio. Nam tempus nunc ut mauris vulputate pretium. Aliquam erat volutpat. Sed viverra accumsan dui. Vivamus eleifend purus nisi, eu suscipit tellus ultrices dictum.\n' +
  '\n' +
  'Proin felis felis, pulvinar vitae eros at, pellentesque posuere erat. Morbi ut erat a magna cursus mollis. Ut sit amet leo ut massa mattis interdum. Mauris porta, felis sed accumsan maximus, lorem dolor rutrum nunc, sit amet pharetra elit neque sed odio. Duis non libero nec est lobortis sollicitudin ac non mauris. Integer auctor, nunc at malesuada dignissim, quam ex porta nibh, non suscipit erat ante ut dolor. Etiam scelerisque finibus orci, ac sodales arcu lacinia at. Maecenas vehicula et urna vel gravida. In id erat bibendum, sodales diam varius, pharetra nibh. Duis venenatis suscipit facilisis. Nunc et ipsum augue.',
  'Curabitur sed sem tortor. Nullam condimentum commodo erat, id tempus turpis euismod quis. Proin leo urna, aliquam vitae eros quis, laoreet fringilla lorem. Etiam tempor turpis ac metus pulvinar gravida. Aenean porttitor imperdiet ipsum, sit amet commodo mi aliquet et. Suspendisse convallis erat eu turpis pretium, ac laoreet nunc hendrerit. Proin ornare nisi quis ultrices viverra. Fusce ut volutpat eros. Praesent ut odio mauris. Donec vel libero finibus, placerat dolor facilisis, auctor massa. Nam mi lorem, tristique id vulputate dignissim, luctus vel urna. Vivamus tempus lacus feugiat, sodales turpis et, rutrum metus. Ut molestie eu libero sed dignissim. Morbi posuere congue malesuada.\n' +
  '\n' +
  'Duis maximus, orci ut dapibus vehicula, metus eros pellentesque lorem, eu tristique justo leo a elit. Sed dui mauris, dictum id est sed, sollicitudin congue massa. Etiam mattis nunc quis libero condimentum, quis convallis lectus rutrum. Phasellus at nibh odio. Ut et fermentum neque. Quisque commodo maximus massa, eget dapibus metus. Integer viverra venenatis nunc, at placerat arcu dapibus eget. Suspendisse in arcu odio. Nam tempus nunc ut mauris vulputate pretium. Aliquam erat volutpat. Sed viverra accumsan dui. Vivamus eleifend purus nisi, eu suscipit tellus ultrices dictum.\n' +
  '\n' +
  'Proin felis felis, pulvinar vitae eros at, pellentesque posuere erat. Morbi ut erat a magna cursus mollis. Ut sit amet leo ut massa mattis interdum. Mauris porta, felis sed accumsan maximus, lorem dolor rutrum nunc, sit amet pharetra elit neque sed odio. Duis non libero nec est lobortis sollicitudin ac non mauris. Integer auctor, nunc at malesuada dignissim, quam ex porta nibh, non suscipit erat ante ut dolor. Etiam scelerisque finibus orci, ac sodales arcu lacinia at. Maecenas vehicula et urna vel gravida. In id erat bibendum, sodales diam varius, pharetra nibh. Duis venenatis suscipit facilisis. Nunc et ipsum augue.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a risus non lacus hendrerit commodo. Vivamus mollis justo sed est accumsan finibus. Integer faucibus, massa at commodo gravida, quam sapien vestibulum urna, efficitur mollis felis mauris ut justo. Praesent sagittis, velit ut dignissim tincidunt, nulla lectus mattis justo, in porta ipsum dolor ac lorem. Suspendisse sagittis, libero vel egestas semper, elit eros sodales magna, vitae ultrices leo eros eget ligula. Etiam urna elit, faucibus nec tellus in, consectetur vestibulum urna. Mauris sodales, ante volutpat commodo facilisis, dolor nunc consequat sapien, a tempor justo tortor et orci. Proin eget suscipit neque. Aenean eleifend sem vel sem fermentum, quis porta lectus ultricies. Sed tincidunt risus lacus, eu laoreet leo faucibus a. Curabitur sagittis nisi sit amet lobortis feugiat.\n' +
  '\n' +
  'Curabitur sit amet purus bibendum, blandit lacus eu, commodo mi. Integer molestie ligula dolor, eget volutpat orci tristique eu. Cras nec pharetra enim. Pellentesque vitae neque at quam malesuada euismod ac at sapien. Etiam eu sapien id nibh sollicitudin volutpat id in erat. Morbi eget erat mi. Phasellus nec tellus aliquam, gravida nisi sit amet, viverra quam.',
  'Donec justo augue, cursus vitae mauris quis, accumsan finibus elit. Nullam semper dapibus quam non gravida. In hac habitasse platea dictumst. Phasellus in mi dolor. Proin sapien ex, egestas vel elit vel, efficitur ultrices mauris. Pellentesque accumsan, orci eget tincidunt rhoncus, ligula lectus porttitor sem, nec commodo metus quam viverra eros. Proin pulvinar neque erat, id sodales eros lacinia sit amet. Fusce vehicula lacus dui. Nam laoreet bibendum gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n' +
  '\n' +
  'Proin id posuere mi. Sed purus lectus, egestas at posuere vitae, malesuada nec dolor. Maecenas ullamcorper nisl arcu, varius porttitor dui congue at. Proin eu dolor a lectus varius pellentesque. Donec congue turpis eu aliquam hendrerit. Curabitur eget elit blandit, suscipit velit vitae, vestibulum est. Sed eu varius augue. Morbi condimentum, enim sed porttitor sollicitudin, ante odio elementum ipsum, ut eleifend nulla odio et quam. Aliquam mattis finibus ligula laoreet tincidunt. Curabitur pharetra magna at turpis aliquet varius. Sed sagittis ac tellus vitae ornare. Donec tempor, quam rutrum luctus sagittis, augue ex iaculis magna, id rutrum magna ipsum a mi. Praesent hendrerit ante risus. In convallis scelerisque sem, posuere sagittis erat mattis sit amet. Phasellus accumsan volutpat nisi vel elementum. Vivamus quis magna orci.',
  'Curabitur mollis tempor nulla sed volutpat. Sed quis nisi sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam rhoncus eu mauris a posuere. Suspendisse varius orci a enim finibus, eu rhoncus sem consectetur. Nunc vel iaculis erat, interdum interdum dolor. Mauris consectetur vehicula felis, ac gravida arcu eleifend pellentesque. Nunc molestie vitae ex ut lacinia. Etiam bibendum augue vel efficitur ultricies. Fusce dignissim tempus feugiat. Sed vitae facilisis nunc, ac tristique justo. Aliquam elementum ac odio vitae lobortis.\n' +
  '\n' +
  'Etiam nec est orci. Nam ex sapien, volutpat non malesuada eget, blandit quis erat. Fusce dictum, massa at volutpat tristique, tortor velit gravida justo, eget gravida elit ex quis nulla. Nam non nisi facilisis est sollicitudin consequat vel ac magna. Morbi feugiat hendrerit nibh a gravida. Fusce semper elit eu urna imperdiet mattis. Aliquam imperdiet neque ac urna tincidunt porta. Nam semper mi a ultricies sagittis.\n' +
  '\n' +
  'Aenean commodo ipsum ligula, non lacinia ex lobortis in. Donec lacinia eget ex vel imperdiet. Cras nunc libero, varius vitae mi vel, rhoncus condimentum turpis. Nullam in sodales eros, euismod ultrices lectus. Etiam porta velit leo, sit amet interdum massa facilisis non. Vestibulum laoreet ex justo, sollicitudin tincidunt libero porttitor nec. Curabitur pretium, nulla ut fermentum gravida, mi velit blandit enim, ut faucibus mauris elit a urna. Pellentesque dapibus ante vitae volutpat consequat. Donec vulputate mattis dolor, eu mattis eros. Morbi elementum nunc et faucibus placerat.\n' +
  '\n' +
  'Nulla facilisi. Sed lobortis iaculis ex, quis mattis odio. Nam non dapibus lorem. Integer ac risus non dolor congue lacinia id id ante. Fusce neque diam, gravida vel varius in, tristique et eros. Duis enim mi, egestas eu tempor finibus, vulputate eget turpis. Vestibulum vitae convallis orci. Praesent ultrices dignissim iaculis. Fusce vitae suscipit mi, malesuada tempus dui. In euismod ultrices est nec dignissim. In pulvinar imperdiet dolor at vulputate. Aenean congue, mauris vel accumsan dignissim, quam eros ornare ex, non pulvinar est sem sit amet felis.\n' +
  '\n' +
  'Nulla ut magna at urna congue dapibus. Ut et venenatis metus, quis finibus leo. Phasellus fringilla libero vitae diam mattis, vitae mollis turpis sollicitudin. Vestibulum eu ante ultricies, posuere ex quis, maximus enim. Integer quis leo et mauris vestibulum sollicitudin quis quis ante. Nullam imperdiet egestas quam. Cras eu massa semper, molestie purus nec, vehicula nisi. Vivamus at eros ac tellus mollis facilisis non vitae urna. Sed tempus viverra mi, id congue quam imperdiet in. Nam molestie iaculis porta.',
];

export default [
  new Petition('0', 'Забудови навколо червоного корпусу!!!', 'Порушення Подиівфв', descriptions[0], 1, 10, new Date(), null),
  new Petition('1', 'Приберіть магаз біля ФРЕКСУ', 'Lorem ipsum asdalsdasd', descriptions[1], 2, 15, new Date(), null),
  new Petition('2', 'Вимагаю звільнення декана факультету Біології!', 'Lorem ipm asdalsdsd', descriptions[2], 1, 100, new Date(), null),
  new Petition('3', 'Басейн на ФізМаті', 'Lorem ipsum aslsdasd', descriptions[3], 2, 10, new Date(), null),
  new Petition('4', 'Куди ділися лисиці з психологічного факу', 'Lorem ipsum alsdasd', descriptions[4], 2, 70, new Date(), null),
  new Petition('5', 'Чорний ястріб на верхівці гори', 'Lorem ipsudalsdasd', descriptions[5], 2, 40, new Date(), null),
  new Petition('6', 'Білозірий монтіфар не алея', 'Lorem  asdalsdasd', descriptions[6], 4, 90, new Date(), null),
  new Petition('7', 'Чому птахи не вилітають з Вулиці', 'Loremsum aasdsdalsdasd', descriptions[7], 4, 21, new Date(), null),
  new Petition('8', 'Майнкрафт челлендж', 'Lorem ipsum asdalsdasd', descriptions[8], 3, 10, new Date(), null),
  new Petition('9', 'Конкурс на кращий музикальний нюх', 'Lorem ipsum asdalsdasd', descriptions[9], 3, 8, new Date(), null),
  new Petition('10', 'Вимагаю виконати обіцянки нового декану Дорошко А.С.', 'Lorem ipsum asdalsdasd', descriptions[10], 1, 1, new Date(), null),
  new Petition('11', 'Коли доцент відповість на запитання які задавав минулого року', 'Lorem ipsum asdalsdasd', descriptions[11], 1, 0, new Date(), null),
];

// export const CategoryTitles = {
//   1: 'Незаконна забудова',
//   2: 'Гіпермаркет',
//   3: 'Третя категорія',
// };

export const CategoryTitles = [
  {id: 1, title: 'Незаконна забудова'},
  {id: 2, title: 'Гіпермаркет'},
  {id: 3, title: 'Третя категорія'},
];
